### ISSUE TITLE
Center the Collectionview inside a StackLayout

### ISSUE THREAD

**Issue by jaspervanmegroot** [muak/AiForms.CollectionView#5]
Is het possible to center the CollectionView? See screenshot:

![file-4](https://user-images.githubusercontent.com/19607572/50156297-beda3200-02ce-11e9-8d5a-7d006f5358f0.jpeg)

**Comment by muak** [comment]
@jaspervanmegroot 

Do you use a HCollectionView?

**Comment by jaspervanmegroot** [comment]
@muak yes

**Comment by jaspervanmegroot** [comment]
Is that possible?

**Comment by muak** [comment]
@jaspervanmegroot 
It is possible if you specify WidthRequest property to any value and HorizontalOptions property to "Center".

```xml
<StackLayout>
    <ai:HCollectionView x:Name="collectionView"
          HorizontalOptions="Center"
          WidthRequest="150"
```
```
