### ISSUE TITLE
GridType in XAML

### ISSUE THREAD

**Issue by donmesserli** [muak/AiForms.CollectionView#6]
Intellisense doesn't seem to work with your CollectionView in XAML files.
When I specify GridType="GridType.UniformGrid" I get an error that the enum doesn't exist.

**Comment by muak** [comment]
@donmesserli 
In the current version of Visual Studio for Mac 2019, the intellisense works in XAML.

In Xaml, how the GridType property is written correctly  is :

```xml
<ai:GridCollectionView GridType="UniformGrid" />
```

Thanks.
