### ISSUE TITLE
Access to ScrollView or Listview

### ISSUE THREAD

**Issue by crashnnburn** [muak/AiForms.CollectionView#9]
Is there a way to access the ScrollView or the ListView of this view? I want to get the position of the Listview using MR.Gestures, but I can't seem to get access to it. I am only able to add behavoirs to Listview, but there isn't any place where Listview is declared.

**Comment by eclipsed4utoo** [comment]
The `CollectionView` is a ListView.

**Comment by muak** [comment]
@eclipsed4utoo 
Thank you for your answer.
